version: "3.8"
services:
  api:
    build: .
    container_name: api
    restart: on-failure
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
    entrypoint: [ "npm", "start" ]
    environment:
      - DATABASE_URL=mysql://root:${DB_PASSWORD}@localhost:3306/goals
      - DB_NAME=goals
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=${PORT}
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    networks:
      - app-connect
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0.28
    platform: linux/x86_64
    container_name: db
    restart: on-failure
    volumes:
      - ./local_database:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - app-connect
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 2s
      retries: 10

networks:
  app-connect:
    driver: bridge